import React, { createContext, useContext, useState, useEffect } from 'react';
import { useQuery } from 'convex/react';
import { api } from '@convex/_generated/api';

type Language = 'pt-BR' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const currentUser = useQuery(api.users.currentUser);

  // Initialize from localStorage or default to pt-BR
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    console.log('[LanguageContext] Initializing with localStorage:', saved);
    return (saved as Language) || 'pt-BR';
  });

  // Load user's saved language preference when user data loads
  useEffect(() => {
    if (currentUser?.language) {
      const userLang = currentUser.language as Language;
      console.log('[LanguageContext] Loading user language from DB:', userLang);
      setLanguageState(userLang);
      localStorage.setItem('language', userLang);
    }
  }, [currentUser?.language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Note: The actual save to database is done in ProfileSection
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translations object
const translations = {
  'pt-BR': {
    common: {
      save: 'Salvar',
      cancel: 'Cancelar',
      delete: 'Excluir',
      edit: 'Editar',
      create: 'Criar',
      search: 'Pesquisar',
      filter: 'Filtrar',
      loading: 'Carregando',
      yes: 'Sim',
      no: 'Não',
      close: 'Fechar',
      back: 'Voltar',
      next: 'Próximo',
      previous: 'Anterior',
      all: 'Todos',
      none: 'Nenhum',
      tasks: 'Tarefas',
      projects: 'Projetos',
      noProjectsYet: 'Nenhum projeto ainda',
      signOut: 'Sair',
      createWorkspace: 'Criar Workspace',
      createWorkspaceDesc: 'Crie um novo workspace para organizar seus projetos e membros da equipe.',
      newProject: 'Novo Projeto',
      createProject: 'Criar Projeto',
    },
    tasks: {
      myTasks: 'Minhas Tarefas',
      projectTasksDesc: 'Visualize e gerencie todas as suas tarefas de projetos',
      assignedTo: 'Atribuído',
      allTasks: 'Todas as Tarefas',
      assignedToMe: 'Atribuídas a Mim',
      project: 'Projeto',
      allProjects: 'Todos os Projetos',
      priority: 'Prioridade',
      allPriorities: 'Todas as Prioridades',
      urgent: 'Urgente',
      high: 'Alta',
      medium: 'Média',
      low: 'Baixa',
      statusFilter: 'Status',
      allStatuses: 'Todos os Status',
      activeTasks: 'Tarefas Ativas',
      sortBy: 'Ordenação',
      dueDate: 'Data de Vencimento',
      viewTask: 'Ver Tarefa',
      noTasksAssigned: 'Nenhuma tarefa atribuída a você',
      createTask: 'Criar Tarefa',
      editTask: 'Editar Tarefa',
      createSubtask: 'Criar Subtarefa',
      updateTaskDetails: 'Atualizar detalhes da tarefa',
      addNewTask: 'Adicionar uma nova tarefa ao seu projeto',
      title: 'Título',
      taskTitle: 'Título da tarefa',
      description: 'Descrição',
      taskDescription: 'Descrição da tarefa',
      status: 'Status',
      toDo: 'A Fazer',
      inProgress: 'Em Progresso',
      review: 'Revisão',
      done: 'Concluído',
      blocked: 'Bloqueado',
      startDate: 'Data de Início',
      estimatedCost: 'Custo Estimado (R$)',
      assignee: 'Responsável',
      selectAssignee: 'Selecione um responsável',
      noAssignee: 'Sem responsável',
      details: 'Detalhes',
      checklist: 'Checklist',
      tags: 'Tags',
      attachments: 'Anexos',
      dependencies: 'Dependências',
      comments: 'Comentários',
      addComment: 'Adicionar um comentário...',
      add: 'Adicionar',
      commentDeleted: 'Comentário excluído',
      failedDeleteComment: 'Falha ao excluir comentário',
      checklistItems: 'Itens de Checklist',
      addChecklistItem: 'Adicionar item de checklist...',
      addTag: 'Adicionar tag',
      createNewTag: 'Criar Nova Tag',
      saveTaskFirst: 'Nota: Salve a tarefa primeiro antes de fazer upload de arquivos',
      delete: 'Excluir',
      cancel: 'Cancelar',
      saveChanges: 'Salvar Alterações',
      newTask: 'Nova Tarefa',
      settings: 'Configurações',
      projectSettings: 'Configurações do Projeto',
      taskAccessControl: 'Controle de Acesso às Tarefas',
      transferManagement: 'Gerenciamento de Transferência',
      members: 'Membros',
      overdue: 'Atrasado',
    },
    dashboard: {
      title: 'Dashboard',
      overview: 'Visão Geral',
      overviewDesc: 'Resumo de todos os seus workspaces, projetos e tarefas',
      myTasks: 'Minhas Tarefas',
      personalTasks: 'Tarefas Pessoais',
      projectTasks: 'Tarefas de Projetos',
      newPersonalTask: 'Nova Tarefa Pessoal',
      totalWorkspaces: 'Total de Workspaces',
      totalProjects: 'Total de Projetos',
      overdueTasks: 'Tarefas Atrasadas',
      overduetasksDesc: 'Tarefas que estão além do prazo',
      upcomingTasks: 'Tarefas Próximas',
      upcomingTasksDesc: 'Tarefas com prazo nos próximos 7 dias',
      recentActivity: 'Atividade Recente',
      recentActivityDesc: 'Últimas atualizações em todos os projetos',
      assignedToYou: 'atribuídas a você',
      taskStatusDistribution: 'Distribuição de Status das Tarefas',
      taskStatusDistributionDesc: 'Visão geral de todas as tarefas em seus projetos',
      onTimeTasks: 'Tarefas no Prazo',
      onTimeTasksDesc: 'Tarefas com prazos futuros',
      noOverdueTasks: 'Nenhuma tarefa atrasada',
      noOnTimeTasks: 'Nenhuma tarefa no prazo',
      noUpcomingTasks: 'Nenhuma tarefa próxima',
      noRecentActivity: 'Nenhuma atividade recente',
      workspaces: 'Workspaces',
      noWorkspacesYet: 'Nenhum workspace ainda',
      workspaceSettings: 'Configurações do workspace',
      deleteWorkspace: 'Excluir workspace',
      noMatchingProjects: 'Nenhum projeto encontrado com os filtros aplicados',
      loadingDashboardData: 'Carregando dados do dashboard...',
      errorLoadingDashboardData: 'Erro ao carregar dados do dashboard',
      reload: 'Recarregar',
      noDueDate: 'Sem data de entrega',
      unnamedProject: 'Projeto sem nome',
    },
    status: {
      toDo: 'A Fazer',
      inProgress: 'Em Progresso',
      review: 'Revisão',
      done: 'Concluído',
      blocked: 'Bloqueado',
    },
    priority: {
      low: 'Baixa',
      medium: 'Média',
      high: 'Alta',
      urgent: 'Urgente',
    },
    profile: {
      title: 'Meu Perfil',
      subtitle: 'Gerencie suas informações pessoais e preferências.',
      personalInfo: 'Informações Pessoais',
      personalInfoDesc: 'Atualize sua foto e detalhes de contato.',
      language: 'Idioma',
      selectLanguage: 'Selecione o idioma',
      name: 'Nome',
      fullName: 'Nome Completo',
      email: 'Email',
      role: 'Função',
      company: 'Empresa',
      selectCompany: 'Selecione sua empresa',
      department: 'Departamento',
      selectDepartment: 'Selecione seu departamento',
      phone: 'Telefone',
      changePhoto: 'Alterar Foto',
      maxFileSize: 'Tamanho máximo de 1MB',
      companySaved: 'Empresa salva!',
      companySaveError: 'Erro ao salvar empresa',
      departmentSaved: 'Departamento salvo!',
      departmentSaveError: 'Erro ao salvar departamento',
      photoUpdated: 'Foto de perfil atualizada com sucesso!',
      photoUpdateError: 'Erro ao atualizar foto de perfil.',
      uploadingImage: 'Enviando imagem...',
      saveChanges: 'Salvar Alterações',
      saving: 'Salvando...',
    },
    company: {
      title: 'Empresa',
      description: 'Gerencie os dados de sua empresa e departamentos.',
      readOnlyMode: 'Você está visualizando em modo de apenas leitura. Apenas administradores podem alterar estes dados.',
      noCompanyFound: 'Nenhuma empresa encontrada.',
      noCompanyFoundDesc: 'Se você já criou uma empresa ou faz parte de uma, verifique se ela está selecionada em seu',
      profile: 'Perfil',
      companyData: 'Dados da Empresa',
      companyDataDesc: 'Informações de registro da empresa.',
      companyName: 'Nome da Empresa',
      companyNamePlaceholder: 'Minha Empresa Ltda.',
      cnpj: 'CNPJ',
      cnpjPlaceholder: '00.000.000/0000-00',
      cep: 'CEP',
      cepPlaceholder: '00000-000',
      number: 'Número',
      numberPlaceholder: '123',
      street: 'Logradouro',
      streetPlaceholder: 'Rua Exemplo',
      neighborhood: 'Bairro',
      neighborhoodPlaceholder: 'Centro',
      city: 'Cidade',
      cityPlaceholder: 'São Paulo',
      state: 'Estado',
      statePlaceholder: 'SP',
      updateData: 'Atualizar Dados',
      registerCompany: 'Cadastrar Empresa',
      companiesRegistered: 'Empresas Cadastradas',
      companiesRegisteredDesc: 'Lista de todas as empresas cadastradas no sistema.',
      departments: 'Departamentos',
      noDepartmentsWithoutCompany: 'Cadastre uma empresa primeiro para gerenciar departamentos.',
      noDepartmentsFound: 'Nenhum departamento cadastrado.',
      name: 'Nome',
      createdAt: 'Criado em',
      companyUpdated: 'Empresa atualizada com sucesso!',
      companyCreated: 'Empresa cadastrada com sucesso!',
      cityUf: 'Cidade/UF',
      noCompaniesYet: 'Nenhuma empresa cadastrada.',
      loadMore: 'Carregar Mais',
      deptNameRequired: 'O nome do departamento é obrigatório.',
      deptAdded: 'Departamento adicionado!',
      deptAlreadyExists: 'Este departamento já existe.',
      deptEmptyName: 'O nome do departamento não pode ser vazio.',
      deptAddError: 'Erro ao adicionar departamento.',
      deptRemoved: 'Departamento removido.',
      deptRemoveError: 'Erro ao remover departamento.',
      deptDescription: 'Gerencie os departamentos da empresa.',
      addDeptPlaceholder: 'Ex: Financeiro',
      deptName: 'Nome do Departamento',
      deptDesc: 'Descrição (Opcional)',
      deptDescPlaceholder: 'Descrição do departamento',
    },
    navigation: {
      home: 'Início',
      dashboard: 'Dashboard',
      tasks: 'Tarefas',
      projects: 'Projetos',
      teams: 'Equipes',
      users: 'Usuários',
      settings: 'Configurações',
      signOut: 'Sair',
    },
    settings: {
      description: 'Gerencie empresas e permissões do sistema',
    },
    permissions: {
      title: 'Permissões',
      description: 'Gerencie o que cada função pode fazer no sistema',
      resetDefaults: 'Resetar Padrões',
      resetConfirm: 'Tem certeza que deseja resetar todas as permissões para o padrão?',
      area: 'Área',
      view: 'Visualizar',
      create: 'Criar',
      edit: 'Editar',
      delete: 'Deletar',
      readOnly: 'Somente Leitura',
      ownerDesc: 'Proprietários têm acesso irrestrito a todas as áreas do sistema.',
      roleDesc: 'Defina as permissões para usuários com a função',
    },
    roles: {
      owner: 'Proprietário',
      manager: 'Gerente',
      collaborator: 'Colaborador',
      reader: 'Leitor',
    },
    users: {
      title: 'Usuários do Sistema',
      description: 'Gerencie usuários e suas funções globais',
      addUser: 'Adicionar Usuário',
      searchUsers: 'Pesquisar usuários...',
      name: 'Nome',
      email: 'Email',
      role: 'Função',
      status: 'Status',
      joined: 'Entrada',
      actions: 'Ações',
      edit: 'Editar',
      block: 'Bloquear',
      unblock: 'Desbloquear',
      delete: 'Excluir',
      blocked: 'Bloqueado',
      active: 'Ativo',
      createUser: 'Criar Novo Usuário',
      createUserDesc: 'Adicionar um novo usuário ao sistema',
      editUser: 'Editar Usuário',
      editUserDesc: 'Atualizar informações do usuário',
      deleteUser: 'Excluir Usuário?',
      deleteUserDesc: 'Esta ação não pode ser desfeita. Isso excluirá permanentemente o usuário e o removerá de todos os workspaces.',
      userRole: 'Função do Usuário',
    },
    teams: {
      title: 'Equipes',
      description: 'Crie e gerencie equipes dentro da sua organização',
      createTeam: 'Criar Equipe',
      searchTeams: 'Pesquisar equipes...',
      teamName: 'Nome da Equipe',
      members: 'Membros',
      created: 'Criado',
      actions: 'Ações',
      edit: 'Editar',
      delete: 'Excluir',
      viewDetails: 'Ver Detalhes',
      noTeams: 'Nenhuma equipe encontrada',
      createNewTeam: 'Criar Nova Equipe',
      createTeamDesc: 'Adicionar uma nova equipe à organização',
      editTeam: 'Editar Equipe',
      editTeamDesc: 'Atualizar informações da equipe',
      deleteTeam: 'Excluir Equipe?',
      deleteTeamDesc: 'Esta ação não pode ser desfeita. Isso excluirá permanentemente a equipe.',
      teamDetails: 'Detalhes da Equipe',
      addMember: 'Adicionar Membro',
      removeMember: 'Remover Membro',
      selectUser: 'Selecionar usuário',
      member: 'membro',
      membersCount: 'membros',
    },
    reminders: {
      title: 'Lembretes por Email',
      description: 'Configure lembretes automáticos por email para seu workspace',
      reminderSettings: 'Configurações de Lembretes',
      reminderSettingsDesc: 'Gerencie quando e como você recebe lembretes de tarefas',
      enableReminders: 'Ativar Lembretes',
      enableRemindersDesc: 'Receba resumos diários de suas tarefas',
      includeOverdue: 'Incluir Tarefas Atrasadas',
      includeOverdueDesc: 'Incluir tarefas que estão além da data de vencimento no lembrete',
      notifyProjectChanges: 'Notificar sobre Mudanças em Projetos',
      notifyProjectChangesDesc: 'Receba emails quando projetos dos quais você faz parte forem atualizados',
      testEmailService: 'Testar Serviço de Email',
      testEmailServiceDesc: 'Envie um email de teste para você mesmo para verificar a configuração',
      sendTest: 'Enviar Teste',
      sending: 'Enviando...',
      recentEmailActivity: 'Atividade Recente de Email',
    },
    invites: {
      title: 'Convites',
      description: 'Gerencie convites de workspace',
      sendInvite: 'Enviar Convite',
      sendInviteDesc: 'Convidar um novo membro para participar de um workspace',
      fullName: 'Nome Completo',
      fullNamePlaceholder: 'João Silva',
      email: 'Email',
      emailPlaceholder: 'usuario@empresa.com',
      workspace: 'Workspace',
      selectWorkspace: 'Selecione um workspace',
      role: 'Função',
      selectRole: 'Selecione uma função',
      sendInviteButton: 'Enviar Convite',
      sending: 'Enviando...',
      pendingInvites: 'Convites Pendentes',
      pendingInvitesDesc: 'Visualize e gerencie convites enviados',
      noPendingInvites: 'Nenhum convite pendente',
      sent: 'Enviado',
      cancel: 'Cancelar',
      unknown: 'Desconhecido',
      pending: 'pendente',
    },

    projects: {
      title: 'Projetos',
      summary: 'Resumo de projetos',
      description: 'Descrição',
      noProjects: 'Nenhum projeto encontrado.',
      projectName: 'Nome do Projeto',
      priority: 'Prioridade',
      startQuarter: 'Trimestre de Início',
      startYear: 'Ano de Início',
      startDate: 'Data de Início',
      endDate: 'Data Final',
      owner: 'Proprietário',
      noOwner: 'Sem proprietário',
      otherOwner: 'Outro usuário',
      noDate: 'Sem data',
      noDescription: 'Sem descrição',
      edit: 'Editar',
      editPriority: 'Editar Prioridade',
      editDescription: 'Editar Descrição',
      setPriority: 'Definir Prioridade',
      descriptionPlaceholder: 'Digite a descrição do projeto...',
      save: 'Salvar',
      cancel: 'Cancelar',
      priorityUpdated: 'Prioridade atualizada com sucesso!',
      priorityUpdateFailed: 'Falha ao atualizar prioridade',
      descriptionUpdated: 'Descrição atualizada com sucesso!',
      descriptionUpdateFailed: 'Falha ao atualizar descrição',
      actions: 'Ações',
      recalculate: 'Recalcular',
      recalculateDates: 'Recalcular Datas',
      datesRecalculated: 'Datas recalculadas com sucesso!',
      datesRecalculationFailed: 'Falha ao recalcular datas',
      open: 'Abrir',
      openProject: 'Abrir Projeto',
      quarterUpdated: 'Trimestre atualizado com sucesso!',
      quarterUpdateFailed: 'Falha ao atualizar trimestre',
      yearUpdated: 'Ano atualizado com sucesso!',
      yearUpdateFailed: 'Falha ao atualizar ano',
      exportToExcel: 'Exportar para Excel',
      exportSuccess: 'Dados exportados com sucesso!',
      noDataToExport: 'Não há dados para exportar',
      searchByName: 'Buscar por nome do projeto',
      searchByOwner: 'Buscar por responsável',
      filterByStatus: 'Filtrar por status',
      allStatuses: 'Todos os Status',
      inProgress: 'Em Andamento',
      approval: 'Aprovação',
      approvalPending: 'Aguardando',
      approvalApproved: 'Aprovado',
      approvalBlocked: 'Bloqueado',
      approvalUpdated: 'Status de aprovação atualizado com sucesso!',
      approvalUpdateFailed: 'Falha ao atualizar status de aprovação',
      paused: 'Pausado',
      finished: 'Concluído',
      noMatchingProjects: 'Nenhum projeto encontrado com os filtros aplicados',
      project: 'projeto',
      projects: 'projetos',
      found: 'encontrado(s)',
      clearFilters: 'Limpar Filtros',
      createProjectDescription: 'Crie um novo projeto dentro deste espaço de trabalho.',
      name: 'Nome',
      namePlaceholder: 'Redesign do Website',
      projectDescriptionPlaceholder: 'Redesenhar o site da empresa com UI moderna',
      color: 'Cor',
      noProjectsYet: 'Ainda não há projetos',
      createFirstProject: 'Crie seu primeiro projeto para começar',
    },
    auth: {
      welcomeBack: 'Bem-vindo de volta',
      createAccount: 'Criar uma conta',
      signInDesc: 'Insira suas credenciais para acessar sua conta',
      signUpDesc: 'Insira seus dados para começar',
      login: 'Login',
      signUp: 'Cadastrar',
      fullName: 'Nome Completo',
      email: 'Email',
      password: 'Senha',
      forgotPassword: 'Esqueceu a senha?',
      signIn: 'Entrar',
      signingIn: 'Entrando...',
      creatingAccount: 'Criando conta...',
      createAccountButton: 'Criar Conta',
      or: 'Ou',
      loginWithEmailCode: 'Entrar com Código por Email',
      resetPassword: 'Redefinir Senha',
      resetPasswordDesc: 'Insira seu email e enviaremos um código para redefinir sua senha.',
      sendResetCode: 'Enviar Código de Redefinição',
      backToLogin: 'Voltar para o Login',
      verifyEmail: 'Verifique seu Email',
      verifyEmailDesc: 'Digite o código enviado para completar seu cadastro.',
      verificationCode: 'Código de Verificação',
      verifying: 'Verificando...',
      verifyCode: 'Verificar Código',
      setNewPassword: 'Definir Nova Senha',
      setNewPasswordDesc: 'Digite o código enviado e sua nova senha.',
      newPassword: 'Nova Senha',
      resetting: 'Redefinindo...',
      checkYourEmail: 'Verifique seu email',
      checkEmailSent: 'Enviamos um código de verificação para',
      tryAgain: 'Tentar novamente',
      didntReceiveCode: 'Não recebeu o código?',
      useDifferentEmail: 'Usar email diferente',
      securedBy: 'Protegido por',
      emailCodeSent: 'Código enviado! Verifique seu email.',
      passwordResetSent: 'Código de redefinição enviado!',
      passwordResetSuccess: 'Senha redefinida com sucesso!',
      accountCreatedSuccess: 'Conta criada com sucesso!',
      loginSuccess: 'Login realizado!',
      enterEmailForCode: 'Por favor, insira seu endereço de email para receber um código de login.',
      invalidCredentials: 'Email ou senha incorretos. Por favor, tente novamente.',
      userNotFound: 'Conta não encontrada. Verifique o email ou crie uma conta.',
      passwordTooShort: 'A senha deve ter pelo menos 8 caracteres.',
      emailInUse: 'Este email já está em uso. Por favor, faça login.',
      requestTimeout: 'A solicitação demorou muito. Verifique sua conexão e tente novamente.',
      networkError: 'Erro de conexão. Verifique sua internet.',
      invalidCode: 'Código de verificação inválido ou expirado.',
      signInFailed: 'Falha no login. Verifique suas credenciais e tente novamente.',
      signUpFailed: 'Não foi possível criar a conta. Revise os dados e tente novamente.',
      otpError: 'Erro ao verificar o código. Tente novamente.',
      resetError: 'Erro ao redefinir a senha. Confira as informações e tente outra vez.',
      unexpectedError: 'Ocorreu um erro inesperado. Tente novamente.',
      passwordMustHaveUpper: 'A senha deve conter pelo menos uma letra maiúscula.',
      passwordMustHaveNumber: 'A senha deve conter pelo menos um número.',
      passwordMustHaveSpecial: 'A senha deve conter pelo menos um caractere especial (!@#$%^&*).',
    },
    landing: {
      projectManagement: 'Gestão de Projetos',
      projectManagementDesc: 'Organize projetos com tarefas, subtarefas e dependências',
      teamCollaboration: 'Colaboração de Equipe',
      teamCollaborationDesc: 'Controle de acesso baseado em funções para grupos de trabalho e projetos',
      multipleViews: 'Múltiplas Visualizações',
      multipleViewsDesc: 'Visualizações de Lista, Calendário, Gantt e quadro Kanban',
      progressTracking: 'Acompanhamento de Progresso',
      progressTrackingDesc: 'Monitore o progresso das tarefas e cronogramas dos projetos',
      heroTitle: 'Gerencie Projetos com',
      heroClarity: ' Clareza',
      heroDesc: 'Gestão de projetos poderosa com RBAC, múltiplas visualizações e integração com Microsoft 365. Construído com princípios do Material Design 3.',
      startFree: 'Começar Grátis',
      learnMore: 'Saiba Mais',
      everythingYouNeed: 'Tudo o que você precisa',
      comprehensiveTools: 'Ferramentas abrangentes para gestão de projetos moderna',
      readyToGetStarted: 'Pronto para começar?',
      joinTeams: 'Junte-se a equipes que usam o ProjecTrak para gerenciar seus projetos com eficiência',
      createFreeAccount: 'Criar Conta Grátis',
      builtWith: 'Desenvolvido por',
      materialDesign: 'Gestão de Projetos em Material Design',
    },
    messages: {
      success: {
        userUpdated: 'Usuário atualizado com sucesso',
        workspaceCreated: 'Workspace criado com sucesso',
        workspaceDeleted: 'Workspace excluído com sucesso',
        projectCreated: 'Projeto criado com sucesso',
        projectStatusUpdated: 'Status do projeto atualizado com sucesso',
        userCreated: 'Usuário criado com sucesso',
        userDeleted: 'Usuário excluído com sucesso',
        userAddedToWorkspace: 'Usuário adicionado ao workspace',
        userRoleUpdated: 'Função do usuário atualizada',
        userUnblocked: 'Usuário desbloqueado com sucesso',
        userBlocked: 'Usuário bloqueado com sucesso',
        teamCreated: 'Time criado com sucesso',
        teamUpdated: 'Time atualizado com sucesso',
        teamDeleted: 'Time excluído com sucesso',
        teamMemberAdded: 'Membro adicionado ao time com sucesso',
        teamMemberRemoved: 'Membro removido do time',
        permissionUpdated: 'Permissão atualizada',
        permissionsReset: 'Permissões resetadas com sucesso',
        inviteSent: 'Convite enviado com sucesso!',
        inviteCancelled: 'Convite cancelado',
        settingsUpdated: 'Configurações atualizadas',
        testEmailSent: 'Email de teste enviado!',
      },
      error: {
        generic: 'Ocorreu um erro. Tente novamente.',
        updateUser: 'Falha ao atualizar usuário',
        createWorkspace: 'Falha ao criar workspace',
        deleteWorkspace: 'Falha ao excluir workspace',
        createProject: 'Falha ao criar projeto',
        updateProjectStatus: 'Falha ao atualizar status do projeto',
        createUser: 'Falha ao criar usuário',
        deleteUser: 'Falha ao excluir usuário',
        addUserToWorkspace: 'Falha ao adicionar usuário ao workspace',
        updateUserRole: 'Falha ao atualizar função do usuário',
        toggleUserBlock: 'Falha ao alterar status de bloqueio do usuário',
        createTeam: 'Falha ao criar time',
        updateTeam: 'Falha ao atualizar time',
        deleteTeam: 'Falha ao excluir time',
        addTeamMember: 'Falha ao adicionar membro ao time',
        removeTeamMember: 'Falha ao remover membro',
        updatePermission: 'Erro ao atualizar permissão',
        resetPermissions: 'Erro ao resetar permissões',
        sendInvite: 'Falha ao enviar convite',
        cancelInvite: 'Falha ao cancelar convite',
        sendTestEmail: 'Falha ao enviar email de teste',
        updateSettings: 'Falha ao atualizar configurações',
        fillAllFields: 'Por favor, preencha todos os campos',
        invalidEmail: 'Por favor, insira um endereço de email válido',
        selectWorkspace: 'Por favor, selecione um workspace',
      }
    }
  },
  en: {
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      search: 'Search',
      filter: 'Filter',
      loading: 'Loading',
      yes: 'Yes',
      no: 'No',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      all: 'All',
      none: 'None',
      tasks: 'Tasks',
      projects: 'Projects',
      noProjectsYet: 'No projects yet',
      signOut: 'Sign Out',
      createWorkspace: 'Create Workspace',
      createWorkspaceDesc: 'Create a new workspace to organize your projects and team members.',
      newProject: 'New Project',
      createProject: 'Create Project',
    },
    tasks: {
      myTasks: 'My Tasks',
      projectTasksDesc: 'View and manage all your project tasks',
      assignedTo: 'Assigned',
      allTasks: 'All Tasks',
      assignedToMe: 'Assigned to Me',
      project: 'Project',
      allProjects: 'All Projects',
      priority: 'Priority',
      allPriorities: 'All Priorities',
      urgent: 'Urgent',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      statusFilter: 'Status',
      allStatuses: 'All Statuses',
      activeTasks: 'Active Tasks',
      sortBy: 'Sort By',
      dueDate: 'Due Date',
      viewTask: 'View Task',
      noTasksAssigned: 'No tasks assigned to you',
      createTask: 'Create Task',
      editTask: 'Edit Task',
      createSubtask: 'Create Subtask',
      updateTaskDetails: 'Update task details',
      addNewTask: 'Add a new task to your project',
      title: 'Title',
      taskTitle: 'Task title',
      description: 'Description',
      taskDescription: 'Task description',
      status: 'Status',
      toDo: 'To Do',
      inProgress: 'In Progress',
      review: 'Review',
      done: 'Done',
      blocked: 'Blocked',
      startDate: 'Start Date',
      estimatedCost: 'Estimated Cost (R$)',
      assignee: 'Assignee',
      selectAssignee: 'Select assignee',
      noAssignee: 'No assignee',
      details: 'Details',
      checklist: 'Checklist',
      tags: 'Tags',
      attachments: 'Attachments',
      dependencies: 'Dependencies',
      comments: 'Comments',
      addComment: 'Add a comment...',
      add: 'Add',
      commentDeleted: 'Comment deleted',
      failedDeleteComment: 'Failed to delete comment',
      checklistItems: 'Checklist Items',
      addChecklistItem: 'Add checklist item...',
      addTag: 'Add tag',
      createNewTag: 'Create New Tag',
      saveTaskFirst: 'Note: Save the task first before uploading files',
      delete: 'Delete',
      cancel: 'Cancel',
      saveChanges: 'Save Changes',
      newTask: 'New Task',
      settings: 'Settings',
      projectSettings: 'Project Settings',
      taskAccessControl: 'Task Access Control',
      transferManagement: 'Transfer Management',
      members: 'Members',
      overdue: 'Overdue',
    },
    dashboard: {
      title: 'Dashboard',
      overview: 'Overview',
      overviewDesc: 'Summary of all your workspaces, projects, and tasks',
      myTasks: 'My Tasks',
      personalTasks: 'Personal Tasks',
      projectTasks: 'Project Tasks',
      newPersonalTask: 'New Personal Task',
      totalWorkspaces: 'Total Workspaces',
      totalProjects: 'Total Projects',
      overdueTasks: 'Overdue Tasks',
      overduetasksDesc: 'Tasks that are past their due date',
      upcomingTasks: 'Upcoming Tasks',
      upcomingTasksDesc: 'Tasks due in the next 7 days',
      recentActivity: 'Recent Activity',
      recentActivityDesc: 'Latest updates across all projects',
      assignedToYou: 'assigned to you',
      taskStatusDistribution: 'Task Status Distribution',
      taskStatusDistributionDesc: 'Overview of all tasks across your projects',
      onTimeTasks: 'On-Time Tasks',
      onTimeTasksDesc: 'Tasks with upcoming due dates',
      noOverdueTasks: 'No overdue tasks',
      noOnTimeTasks: 'No on-time tasks',
      noUpcomingTasks: 'No upcoming tasks',
      noRecentActivity: 'No recent activity',
      workspaces: 'Workspaces',
      noWorkspacesYet: 'No workspaces yet',
      workspaceSettings: 'Workspace settings',
      deleteWorkspace: 'Delete workspace',
      noMatchingProjects: 'No matching projects found with the applied filters',
      loadingDashboardData: 'Loading dashboard data...',
      errorLoadingDashboardData: 'Error loading dashboard data',
      reload: 'Reload',
      noDueDate: 'No due date',
      unnamedProject: 'Unnamed project',
    },
    status: {
      toDo: 'To Do',
      inProgress: 'In Progress',
      review: 'Review',
      done: 'Done',
      blocked: 'Blocked',
    },
    priority: {
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
    },
    profile: {
      title: 'My Profile',
      subtitle: 'Manage your personal information and preferences.',
      personalInfo: 'Personal Information',
      personalInfoDesc: 'Update your photo and contact details.',
      language: 'Language',
      selectLanguage: 'Select language',
      name: 'Name',
      fullName: 'Full Name',
      email: 'Email',
      role: 'Role',
      company: 'Company',
      selectCompany: 'Select your company',
      department: 'Department',
      selectDepartment: 'Select your department',
      phone: 'Phone',
      changePhoto: 'Change Photo',
      uploadingImage: 'Uploading image...',
      saveChanges: 'Save Changes',
      saving: 'Saving...',
      maxFileSize: 'Maximum 5MB',
    },
    navigation: {
      home: 'Home',
      dashboard: 'Dashboard',
      tasks: 'Tasks',
      projects: 'Projects',
      teams: 'Teams',
      users: 'Users',
      settings: 'Settings',
      signOut: 'Sign Out',
    },
    settings: {
      description: 'Manage companies and system permissions',
    },
    permissions: {
      title: 'Permissions',
      description: 'Manage what each role can do in the system',
      resetDefaults: 'Reset Defaults',
      resetConfirm: 'Are you sure you want to reset all permissions to default?',
      area: 'Area',
      view: 'View',
      create: 'Create',
      edit: 'Edit',
      delete: 'Delete',
      readOnly: 'Read Only',
      ownerDesc: 'Owners have unrestricted access to all areas of the system.',
      roleDesc: 'Define permissions for users with the role',
    },
    roles: {
      owner: 'Owner',
      manager: 'Manager',
      collaborator: 'Collaborator',
      reader: 'Reader',
    },
    users: {
      title: 'System Users',
      description: 'Manage users and their global roles',
      addUser: 'Add User',
      searchUsers: 'Search users...',
      name: 'Name',
      email: 'Email',
      role: 'Role',
      status: 'Status',
      joined: 'Joined',
      actions: 'Actions',
      edit: 'Edit',
      block: 'Block',
      unblock: 'Unblock',
      delete: 'Delete',
      blocked: 'Blocked',
      active: 'Active',
      createUser: 'Create New User',
      createUserDesc: 'Add a new user to the system',
      editUser: 'Edit User',
      editUserDesc: 'Update user information',
      deleteUser: 'Are you sure?',
      deleteUserDesc: 'This action cannot be undone. This will permanently delete the user and remove them from all workspaces.',
      userRole: 'User Role',
    },
    teams: {
      title: 'Teams',
      description: 'Create and manage teams within your organization',
      createTeam: 'Create Team',
      searchTeams: 'Search teams...',
      teamName: 'Team Name',
      members: 'Members',
      created: 'Created',
      actions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      viewDetails: 'View Details',
      noTeams: 'No teams found',
      createNewTeam: 'Create New Team',
      createTeamDesc: 'Add a new team to the organization',
      editTeam: 'Edit Team',
      editTeamDesc: 'Update team information',
      deleteTeam: 'Delete Team?',
      deleteTeamDesc: 'This action cannot be undone. This will permanently delete the team.',
      teamDetails: 'Team Details',
      addMember: 'Add Member',
      removeMember: 'Remove Member',
      selectUser: 'Select user',
      member: 'member',
      membersCount: 'members',
    },
    reminders: {
      title: 'Email Reminders',
      description: 'Configure automated email reminders for your workspace',
      reminderSettings: 'Reminder Settings',
      reminderSettingsDesc: 'Manage when and how you receive task reminders',
      enableReminders: 'Enable Reminders',
      enableRemindersDesc: 'Receive daily summaries of your tasks',
      includeOverdue: 'Include Overdue Tasks',
      includeOverdueDesc: 'Include tasks that are past their due date in the reminder',
      notifyProjectChanges: 'Notify on Project Changes',
      notifyProjectChangesDesc: 'Receive emails when projects you are part of are updated',
      testEmailService: 'Test Email Service',
      testEmailServiceDesc: 'Send a test email to yourself to verify configuration',
      sendTest: 'Send Test',
      sending: 'Sending...',
      recentEmailActivity: 'Recent Email Activity',
    },
    invites: {
      title: 'Invites',
      description: 'Manage workspace invitations',
      sendInvite: 'Send Invite',
      sendInviteDesc: 'Invite a new member to join a workspace',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Silva',
      email: 'Email',
      emailPlaceholder: 'user@company.com',
      workspace: 'Workspace',
      selectWorkspace: 'Select a workspace',
      role: 'Role',
      selectRole: 'Select a role',
      sendInviteButton: 'Send Invite',
      sending: 'Sending...',
      pendingInvites: 'Pending Invites',
      pendingInvitesDesc: 'View and manage sent invitations',
      noPendingInvites: 'No pending invites',
      sent: 'Sent',
      cancel: 'Cancel',
      unknown: 'Unknown',
      pending: 'pending',
    },
    company: {
      title: 'Company',
      description: 'Manage your company data and departments.',
      readOnlyMode: 'You are viewing in read-only mode. Only administrators can change this data.',
      noCompanyFound: 'No company found.',
      noCompanyFoundDesc: 'If you have already created a company or are part of one, check if it is selected in your',
      profile: 'Profile',
      companyData: 'Company Data',
      companyDataDesc: 'Company registration information.',
      companyName: 'Company Name',
      companyNamePlaceholder: 'My Company Ltd',
      cnpj: 'Tax ID',
      cnpjPlaceholder: '00-0000000',
      cep: 'ZIP Code',
      cepPlaceholder: '00000',
      number: 'Number',
      numberPlaceholder: '123',
      street: 'Street',
      streetPlaceholder: 'Example Street',
      neighborhood: 'Neighborhood',
      neighborhoodPlaceholder: 'Downtown',
      city: 'City',
      cityPlaceholder: 'New York',
      state: 'State',
      statePlaceholder: 'NY',
      updateData: 'Update Data',
      registerCompany: 'Register Company',
      companiesRegistered: 'Registered Companies',
      companiesRegisteredDesc: 'List of all companies registered in the system.',
      departments: 'Departments',
      noDepartmentsWithoutCompany: 'Register a company first to manage departments.',
      noDepartmentsFound: 'No departments registered.',
      name: 'Name',
      createdAt: 'Created at',
      companyUpdated: 'Company updated successfully!',
      companyCreated: 'Company registered successfully!',
      cityUf: 'City/UF',
      noCompaniesYet: 'No companies registered.',
      loadMore: 'Load More',
      deptNameRequired: 'Department name is required.',
      deptAdded: 'Department added!',
      deptAlreadyExists: 'This department already exists.',
      deptEmptyName: 'Department name cannot be empty.',
      deptAddError: 'Error adding department.',
      deptRemoved: 'Department removed.',
      deptRemoveError: 'Error removing department.',
      deptDescription: 'Manage company departments.',
      addDeptPlaceholder: 'Ex: Finance',
      deptName: 'Department Name',
      deptDesc: 'Description (Optional)',
      deptDescPlaceholder: 'Department description',
    },
    projects: {
      title: 'Projects',
      summary: 'Projects Summary',
      description: 'Description',
      noProjects: 'No projects found.',
      projectName: 'Project Name',
      priority: 'Priority',
      startDate: 'Start Date',
      endDate: 'End Date',
      owner: 'Owner',
      noOwner: 'No owner',
      otherOwner: 'Other user',
      noDate: 'No date',
      noDescription: 'No description',
      edit: 'Edit',
      editPriority: 'Edit Priority',
      editDescription: 'Edit Description',
      setPriority: 'Set Priority',
      descriptionPlaceholder: 'Enter project description...',
      save: 'Save',
      cancel: 'Cancel',
      priorityUpdated: 'Priority updated successfully!',
      priorityUpdateFailed: 'Failed to update priority',
      descriptionUpdated: 'Description updated successfully!',
      descriptionUpdateFailed: 'Failed to update description',
      actions: 'Actions',
      recalculate: 'Recalculate',
      recalculateDates: 'Recalculate Dates',
      datesRecalculated: 'Dates recalculated successfully!',
      datesRecalculationFailed: 'Failed to recalculate dates',
      open: 'Open',
      openProject: 'Open Project',
      createProjectDescription: 'Create a new project within this workgroup.',
      name: 'Name',
      namePlaceholder: 'Website Redesign',
      projectDescriptionPlaceholder: 'Redesign the company website with modern UI',
      color: 'Color',
      noProjectsYet: 'No projects yet',
      createFirstProject: 'Create your first project to get started',
      startQuarter: 'Start Quarter',
      startYear: 'Start Year',
      quarterUpdated: 'Quarter updated successfully!',
      quarterUpdateFailed: 'Failed to update quarter',
      yearUpdated: 'Year updated successfully!',
      yearUpdateFailed: 'Failed to update year',
      exportToExcel: 'Export to Excel',
      exportSuccess: 'Data exported successfully!',
      noDataToExport: 'No data to export',
      searchByName: 'Search by project name',
      searchByOwner: 'Search by owner',
      filterByStatus: 'Filter by status',
      allStatuses: 'All Statuses',
      inProgress: 'In Progress',
      approval: 'Approval',
      approvalPending: 'Pending',
      approvalApproved: 'Approved',
      approvalBlocked: 'Blocked',
      approvalUpdated: 'Approval status updated successfully!',
      approvalUpdateFailed: 'Failed to update approval status',
      paused: 'Paused',
      finished: 'Finished',
      noMatchingProjects: 'No projects found with the applied filters',
      project: 'project',
      projects: 'projects',
      found: 'found',
      clearFilters: 'Clear Filters',
    },
    auth: {
      welcomeBack: 'Welcome back',
      createAccount: 'Create an account',
      signInDesc: 'Enter your credentials to access your account',
      signUpDesc: 'Enter your details to get started',
      login: 'Login',
      signUp: 'Sign Up',
      fullName: 'Full Name',
      email: 'Email',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      creatingAccount: 'Creating account...',
      createAccountButton: 'Create Account',
      or: 'Or',
      loginWithEmailCode: 'Login with Email Code',
      resetPassword: 'Reset Password',
      resetPasswordDesc: "Enter your email address and we'll send you a code to reset your password.",
      sendResetCode: 'Send Reset Code',
      backToLogin: 'Back to Login',
      verifyEmail: 'Verify your Email',
      verifyEmailDesc: 'Enter the code sent to complete your registration.',
      verificationCode: 'Verification Code',
      verifying: 'Verifying...',
      verifyCode: 'Verify Code',
      setNewPassword: 'Set New Password',
      setNewPasswordDesc: 'Enter the code sent and your new password.',
      newPassword: 'New Password',
      resetting: 'Resetting...',
      checkYourEmail: 'Check your email',
      checkEmailSent: "We've sent a verification code to",
      tryAgain: 'Try again',
      didntReceiveCode: "Didn't receive a code?",
      useDifferentEmail: 'Use different email',
      securedBy: 'Secured by',
      emailCodeSent: 'Code sent! Check your email.',
      passwordResetSent: 'Reset code sent!',
      passwordResetSuccess: 'Password reset successfully!',
      accountCreatedSuccess: 'Account created successfully!',
      loginSuccess: 'Logged in!',
      enterEmailForCode: 'Please enter your email address to receive a login code.',
      invalidCredentials: 'Incorrect email or password. Please try again.',
      userNotFound: 'Account not found. Check the email or create an account.',
      passwordTooShort: 'Password must be at least 8 characters long.',
      emailInUse: 'This email is already in use. Please log in.',
      requestTimeout: 'Request timed out. Check your connection and try again.',
      networkError: 'Connection error. Check your internet.',
      invalidCode: 'Invalid or expired verification code.',
      signInFailed: 'Login failed. Check your credentials and try again.',
      signUpFailed: 'Could not create account. Review the data and try again.',
      otpError: 'Error verifying code. Try again.',
      resetError: 'Error resetting password. Check the information and try again.',
      unexpectedError: 'An unexpected error occurred. Try again.',
      passwordMustHaveUpper: 'Password must contain at least one uppercase letter.',
      passwordMustHaveNumber: 'Password must contain at least one number.',
      passwordMustHaveSpecial: 'Password must contain at least one special character (!@#$%^&*).',
    },
    landing: {
      projectManagement: 'Project Management',
      projectManagementDesc: 'Organize projects with tasks, subtasks, and dependencies',
      teamCollaboration: 'Team Collaboration',
      teamCollaborationDesc: 'Role-based access control for workgroups and projects',
      multipleViews: 'Multiple Views',
      multipleViewsDesc: 'List, Calendar, Gantt, and Kanban board views',
      progressTracking: 'Progress Tracking',
      progressTrackingDesc: 'Monitor task progress and project timelines',
      heroTitle: 'Manage Projects with',
      heroClarity: ' Clarity',
      heroDesc: 'Powerful project management with RBAC, multiple views, and Microsoft 365 integration. Built with Material Design 3 principles.',
      startFree: 'Start Free',
      learnMore: 'Learn More',
      everythingYouNeed: 'Everything you need',
      comprehensiveTools: 'Comprehensive tools for modern project management',
      readyToGetStarted: 'Ready to get started?',
      joinTeams: 'Join teams using ProjecTrak to manage their projects efficiently',
      createFreeAccount: 'Create Free Account',
      builtWith: 'Built with',
      materialDesign: 'Material Design Project Management',
    },
    messages: {
      success: {
        userUpdated: 'User updated successfully',
        workspaceCreated: 'Workspace created successfully',
        workspaceDeleted: 'Workspace deleted successfully',
        projectCreated: 'Project created successfully',
        projectStatusUpdated: 'Project status updated successfully',
        userCreated: 'User created successfully',
        userDeleted: 'User deleted successfully',
        userAddedToWorkspace: 'User added to workspace',
        userRoleUpdated: 'User role updated',
        userUnblocked: 'User unblocked successfully',
        userBlocked: 'User blocked successfully',
        teamCreated: 'Team created successfully',
        teamUpdated: 'Team updated successfully',
        teamDeleted: 'Team deleted successfully',
        teamMemberAdded: 'Team member added successfully',
        teamMemberRemoved: 'Member removed from team',
        permissionUpdated: 'Permission updated',
        permissionsReset: 'Permissions reset successfully',
        inviteSent: 'Invite sent successfully!',
        inviteCancelled: 'Invite cancelled',
        settingsUpdated: 'Settings updated',
        testEmailSent: 'Test email sent!',
      },
      error: {
        generic: 'An error occurred. Please try again.',
        updateUser: 'Failed to update user',
        createWorkspace: 'Failed to create workspace',
        deleteWorkspace: 'Failed to delete workspace',
        createProject: 'Failed to create project',
        updateProjectStatus: 'Failed to update project status',
        createUser: 'Failed to create user',
        deleteUser: 'Failed to delete user',
        addUserToWorkspace: 'Failed to add user to workspace',
        updateUserRole: 'Failed to update user role',
        toggleUserBlock: 'Failed to toggle user block status',
        createTeam: 'Failed to create team',
        updateTeam: 'Failed to update team',
        deleteTeam: 'Failed to delete team',
        addTeamMember: 'Failed to add team member',
        removeTeamMember: 'Failed to remove member',
        updatePermission: 'Error updating permission',
        resetPermissions: 'Error resetting permissions',
        sendInvite: 'Failed to send invite',
        cancelInvite: 'Failed to cancel invite',
        sendTestEmail: 'Failed to send test email',
        updateSettings: 'Failed to update settings',
        fillAllFields: 'Please fill in all fields',
        invalidEmail: 'Please enter a valid email address',
        selectWorkspace: 'Please select a workgroup',
      }
    }
  },
  es: {
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      create: 'Crear',
      search: 'Buscar',
      filter: 'Filtrar',
      loading: 'Cargando',
      yes: 'Sí',
      no: 'No',
      close: 'Cerrar',
      back: 'Atrás',
      next: 'Siguiente',
      previous: 'Anterior',
      all: 'Todos',
      none: 'Ninguno',
      tasks: 'Tareas',
      projects: 'Proyectos',
      noProjectsYet: 'Aún no hay proyectos',
      signOut: 'Cerrar Sesión',
      createWorkspace: 'Crear Workspace',
      createWorkspaceDesc: 'Crea un nuevo workspace para organizar tus proyectos y miembros del equipo.',
      newProject: 'Nuevo Proyecto',
      createProject: 'Crear Proyecto',
    },
    tasks: {
      myTasks: 'Mis Tareas',
      projectTasksDesc: 'Ver y gestionar todas tus tareas de proyectos',
      assignedTo: 'Asignado',
      allTasks: 'Todas las Tareas',
      assignedToMe: 'Asignadas a Mí',
      project: 'Proyecto',
      allProjects: 'Todos los Proyectos',
      priority: 'Prioridad',
      allPriorities: 'Todas las Prioridades',
      urgent: 'Urgente',
      high: 'Alta',
      medium: 'Media',
      low: 'Baja',
      statusFilter: 'Estado',
      allStatuses: 'Todos los Estados',
      activeTasks: 'Tareas Activas',
      sortBy: 'Ordenar por',
      dueDate: 'Fecha de Vencimiento',
      viewTask: 'Ver Tarea',
      noTasksAssigned: 'No hay tareas asignadas a ti',
      createTask: 'Crear Tarea',
      editTask: 'Editar Tarea',
      createSubtask: 'Crear Subtarea',
      updateTaskDetails: 'Actualizar detalles de la tarea',
      addNewTask: 'Agregar una nueva tarea a tu proyecto',
      title: 'Título',
      taskTitle: 'Título de la tarea',
      description: 'Descripción',
      taskDescription: 'Descripción de la tarea',
      status: 'Estado',
      toDo: 'Por Hacer',
      inProgress: 'En Progreso',
      review: 'Revisión',
      done: 'Completado',
      blocked: 'Bloqueado',
      startDate: 'Fecha de Inicio',
      estimatedCost: 'Costo Estimado (R$)',
      assignee: 'Responsable',
      selectAssignee: 'Seleccionar responsable',
      noAssignee: 'Sin responsable',
      details: 'Detalles',
      checklist: 'Checklist',
      tags: 'Etiquetas',
      attachments: 'Adjuntos',
      dependencies: 'Dependencias',
      comments: 'Comentarios',
      addComment: 'Agregar un comentario...',
      add: 'Agregar',
      commentDeleted: 'Comentario eliminado',
      failedDeleteComment: 'Error al eliminar comentario',
      checklistItems: 'Elementos de Checklist',
      addChecklistItem: 'Agregar elemento de checklist...',
      addTag: 'Agregar etiqueta',
      createNewTag: 'Crear Nueva Etiqueta',
      saveTaskFirst: 'Nota: Guarda la tarea primero antes de subir archivos',
      delete: 'Eliminar',
      cancel: 'Cancelar',
      saveChanges: 'Guardar Cambios',
      newTask: 'Nueva Tarea',
      settings: 'Configuración',
      projectSettings: 'Configuración del Proyecto',
      taskAccessControl: 'Control de Acceso a Tareas',
      transferManagement: 'Gestión de Transferencia',
      members: 'Miembros',
      overdue: 'Atrasado',
    },
    dashboard: {
      title: 'Panel de Control',
      overview: 'Resumen',
      overviewDesc: 'Resumen de todos tus espacios de trabajo, proyectos y tareas',
      myTasks: 'Mis Tareas',
      personalTasks: 'Tareas Personales',
      projectTasks: 'Tareas de Proyectos',
      newPersonalTask: 'Nueva Tarea Personal',
      totalWorkspaces: 'Total de Espacios',
      totalProjects: 'Total de Proyectos',
      overdueTasks: 'Tareas Atrasadas',
      overduetasksDesc: 'Tareas que han pasado su fecha límite',
      upcomingTasks: 'Próximas Tareas',
      upcomingTasksDesc: 'Tareas con fecha límite en los próximos 7 días',
      recentActivity: 'Actividad Reciente',
      recentActivityDesc: 'Últimas actualizaciones en todos los proyectos',
      assignedToYou: 'asignadas a ti',
      taskStatusDistribution: 'Distribución de Estado de Tareas',
      taskStatusDistributionDesc: 'Vista general de todas las tareas en tus proyectos',
      onTimeTasks: 'Tareas a Tiempo',
      onTimeTasksDesc: 'Tareas con fechas límite próximas',
      noOverdueTasks: 'No hay tareas atrasadas',
      noOnTimeTasks: 'No hay tareas a tiempo',
      noUpcomingTasks: 'No hay tareas próximas',
      noRecentActivity: 'No hay actividad reciente',
    },
    status: {
      toDo: 'Por Hacer',
      inProgress: 'En Progreso',
      review: 'Revisión',
      done: 'Completado',
      blocked: 'Bloqueado',
    },
    priority: {
      low: 'Baja',
      medium: 'Media',
      high: 'Alta',
      urgent: 'Urgente',
    },
    profile: {
      title: 'Mi Perfil',
      subtitle: 'Gestiona tu información personal y preferencias.',
      personalInfo: 'Información Personal',
      personalInfoDesc: 'Actualiza tu foto y detalles de contacto.',
      language: 'Idioma',
      selectLanguage: 'Seleccionar idioma',
      name: 'Nombre',
      fullName: 'Nombre Completo',
      email: 'Correo',
      role: 'Rol',
      company: 'Empresa',
      selectCompany: 'Selecciona tu empresa',
      department: 'Departamento',
      selectDepartment: 'Selecciona tu departamento',
      phone: 'Teléfono',
      changePhoto: 'Cambiar Foto',
      uploadingImage: 'Subiendo imagen...',
      saveChanges: 'Guardar Cambios',
      saving: 'Guardando...',
      maxFileSize: 'Máximo 5MB',
    },
    navigation: {
      home: 'Inicio',
      dashboard: 'Panel',
      tasks: 'Tareas',
      projects: 'Proyectos',
      teams: 'Equipos',
      users: 'Usuarios',
      settings: 'Configuración',
      signOut: 'Cerrar Sesión',
    },
    settings: {
      description: 'Gestionar empresas y permisos del sistema',
    },
    permissions: {
      title: 'Permisos',
      description: 'Gestiona lo que cada rol puede hacer en el sistema',
      resetDefaults: 'Restaurar Predeterminados',
      resetConfirm: '¿Está seguro de que desea restaurar todos los permisos a los valores predeterminados?',
      area: 'Área',
      view: 'Ver',
      create: 'Crear',
      edit: 'Editar',
      delete: 'Eliminar',
      readOnly: 'Solo Lectura',
      ownerDesc: 'Los propietarios tienen acceso sin restricciones a todas las áreas del sistema.',
      roleDesc: 'Define permisos para usuarios con el rol',
    },
    roles: {
      owner: 'Propietario',
      manager: 'Gerente',
      collaborator: 'Colaborador',
      reader: 'Lector',
    },
    users: {
      title: 'Usuarios del Sistema',
      description: 'Gestiona usuarios y sus roles globales',
      addUser: 'Agregar Usuario',
      searchUsers: 'Buscar usuarios...',
      name: 'Nombre',
      email: 'Correo',
      role: 'Rol',
      status: 'Estado',
      joined: 'Ingreso',
      actions: 'Acciones',
      edit: 'Editar',
      block: 'Bloquear',
      unblock: 'Desbloquear',
      delete: 'Eliminar',
      blocked: 'Bloqueado',
      active: 'Activo',
      createUser: 'Crear Nuevo Usuario',
      createUserDesc: 'Agregar un nuevo usuario al sistema',
      editUser: 'Editar Usuario',
      editUserDesc: 'Actualizar información del usuario',
      deleteUser: '¿Está seguro?',
      deleteUserDesc: 'Esta acción no se puede deshacer. Esto eliminará permanentemente al usuario y lo removerá de todos los espacios de trabajo.',
      userRole: 'Rol del Usuario',
    },
    teams: {
      title: 'Equipos',
      description: 'Crea y gestiona equipos dentro de tu organización',
      createTeam: 'Crear Equipo',
      searchTeams: 'Buscar equipos...',
      teamName: 'Nombre del Equipo',
      members: 'Miembros',
      created: 'Creado',
      actions: 'Acciones',
      edit: 'Editar',
      delete: 'Eliminar',
      viewDetails: 'Ver Detalles',
      noTeams: 'No se encontraron equipos',
      createNewTeam: 'Crear Nuevo Equipo',
      createTeamDesc: 'Agregar un nuevo equipo a la organización',
      editTeam: 'Editar Equipo',
      editTeamDesc: 'Actualizar información del equipo',
      deleteTeam: '¿Eliminar Equipo?',
      deleteTeamDesc: 'Esta acción no se puede deshacer. Esto eliminará permanentemente el equipo.',
      teamDetails: 'Detalles del Equipo',
      addMember: 'Agregar Miembro',
      removeMember: 'Remover Miembro',
      selectUser: 'Seleccionar usuario',
      member: 'miembro',
      membersCount: 'miembros',
    },
    reminders: {
      title: 'Recordatorios por Email',
      description: 'Configura recordatorios automáticos por email para tu espacio de trabajo',
      reminderSettings: 'Configuración de Recordatorios',
      reminderSettingsDesc: 'Gestiona cuándo y cómo recibes recordatorios de tareas',
      enableReminders: 'Activar Recordatorios',
      enableRemindersDesc: 'Recibe resúmenes diarios de tus tareas',
      includeOverdue: 'Incluir Tareas Atrasadas',
      includeOverdueDesc: 'Incluir tareas que han pasado su fecha límite en el recordatorio',
      notifyProjectChanges: 'Notificar sobre Cambios en Proyectos',
      notifyProjectChangesDesc: 'Recibe emails cuando se actualicen proyectos de los que formas parte',
      testEmailService: 'Probar Servicio de Email',
      testEmailServiceDesc: 'Envía un email de prueba a ti mismo para verificar la configuración',
      sendTest: 'Enviar Prueba',
      sending: 'Enviando...',
      recentEmailActivity: 'Actividad Reciente de Email',
    },
    invites: {
      title: 'Invitaciones',
      description: 'Gestiona invitaciones de workspace',
      sendInvite: 'Enviar Invitación',
      sendInviteDesc: 'Invitar a un nuevo miembro a unirse a un workspace',
      fullName: 'Nombre Completo',
      fullNamePlaceholder: 'Juan Silva',
      email: 'Email',
      emailPlaceholder: 'usuario@empresa.com',
      workspace: 'Workspace',
      selectWorkspace: 'Selecciona un workspace',
      role: 'Rol',
      selectRole: 'Selecciona un rol',
      sendInviteButton: 'Enviar Invitación',
      sending: 'Enviando...',
      pendingInvites: 'Invitaciones Pendientes',
      pendingInvitesDesc: 'Ver y gestionar invitaciones enviadas',
      noPendingInvites: 'No hay invitaciones pendientes',
      sent: 'Enviado',
      cancel: 'Cancelar',
      unknown: 'Desconocido',
      pending: 'pendiente',
    },
    company: {
      title: 'Empresa',
      description: 'Gestiona los datos de tu empresa y departamentos.',
      readOnlyMode: 'Estás viendo en modo de solo lectura. Solo los administradores pueden cambiar estos datos.',
      noCompanyFound: 'No se encontró empresa.',
      noCompanyFoundDesc: 'Si ya has creado una empresa o formas parte de una, verifica si está seleccionada en tu',
      profile: 'Perfil',
      companyData: 'Datos de la Empresa',
      companyDataDesc: 'Información de registro de la empresa.',
      companyName: 'Nombre de la Empresa',
      companyNamePlaceholder: 'Mi Empresa S.L.',
      cnpj: 'NIF/CIF',
      cnpjPlaceholder: 'A00000000',
      cep: 'Código Postal',
      cepPlaceholder: '00000',
      number: 'Número',
      numberPlaceholder: '123',
      street: 'Calle',
      streetPlaceholder: 'Calle Ejemplo',
      neighborhood: 'Barrio',
      neighborhoodPlaceholder: 'Centro',
      city: 'Ciudad',
      cityPlaceholder: 'Madrid',
      state: 'Provincia',
      statePlaceholder: 'MD',
      updateData: 'Actualizar Datos',
      registerCompany: 'Registrar Empresa',
      companiesRegistered: 'Empresas Registradas',
      companiesRegisteredDesc: 'Lista de todas las empresas registradas en el sistema.',
      departments: 'Departamentos',
      noDepartmentsWithoutCompany: 'Registra una empresa primero para gestionar departamentos.',
      name: 'Nombre',
      createdAt: 'Creado el',
      companyUpdated: '¡Empresa actualizada con éxito!',
      companyCreated: '¡Empresa registrada con éxito!',
    },
    projects: {
      title: 'Proyectos',
      summary: 'Resumen de proyectos',
      description: 'Descripción',
      noProjects: 'No se encontraron proyectos.',
      projectName: 'Nombre del Proyecto',
      priority: 'Prioridad',
      startDate: 'Fecha de Inicio',
      endDate: 'Fecha Final',
      owner: 'Propietario',
      noOwner: 'Sin propietario',
      otherOwner: 'Otro usuario',
      noDate: 'Sin fecha',
      noDescription: 'Sin descripción',
      edit: 'Editar',
      editPriority: 'Editar Prioridad',
      editDescription: 'Editar Descripción',
      setPriority: 'Establecer Prioridad',
      descriptionPlaceholder: 'Ingrese la descripción del proyecto...',
      save: 'Guardar',
      cancel: 'Cancelar',
      priorityUpdated: '¡Prioridad actualizada con éxito!',
      priorityUpdateFailed: 'Error al actualizar prioridad',
      descriptionUpdated: '¡Descripción actualizada con éxito!',
      descriptionUpdateFailed: 'Error al actualizar descripción',
      actions: 'Acciones',
      recalculate: 'Recalcular',
      recalculateDates: 'Recalcular Fechas',
      datesRecalculated: '¡Fechas recalculadas con éxito!',
      datesRecalculationFailed: 'Error al recalcular fechas',
      open: 'Abrir',
      openProject: 'Abrir Proyecto',
      createProjectDescription: 'Crea un nuevo proyecto dentro de este espacio de trabajo.',
      name: 'Nombre',
      namePlaceholder: 'Rediseño del Sitio Web',
      projectDescriptionPlaceholder: 'Rediseñar el sitio web de la empresa con UI moderna',
      color: 'Color',
      noProjectsYet: 'Aún no hay proyectos',
      createFirstProject: 'Crea tu primer proyecto para comenzar',
      startQuarter: 'Trimestre de Inicio',
      startYear: 'Año de Inicio',
      quarterUpdated: '¡Trimestre actualizado con éxito!',
      quarterUpdateFailed: 'Error al actualizar trimestre',
      yearUpdated: '¡Año actualizado con éxito!',
      yearUpdateFailed: 'Error al actualizar año',
      exportToExcel: 'Exportar a Excel',
      exportSuccess: '¡Datos exportados con éxito!',
      noDataToExport: 'No hay datos para exportar',
      searchByName: 'Buscar por nombre del proyecto',
      searchByOwner: 'Buscar por responsable',
      filterByStatus: 'Filtrar por estado',
      allStatuses: 'Todos los Estados',
      inProgress: 'En Progreso',
      approval: 'Aprobación',
      approvalPending: 'Pendiente',
      approvalApproved: 'Aprobado',
      approvalBlocked: 'Bloqueado',
      approvalUpdated: '¡Estado de aprobación actualizado con éxito!',
      approvalUpdateFailed: 'Error al actualizar estado de aprobación',
      paused: 'Pausado',
      finished: 'Finalizado',
      noMatchingProjects: 'No se encontraron proyectos con los filtros aplicados',
      project: 'proyecto',
      projects: 'proyectos',
      found: 'encontrado(s)',
      clearFilters: 'Limpiar Filtros',
    },
    auth: {
      welcomeBack: 'Bienvenido de nuevo',
      createAccount: 'Crear una cuenta',
      signInDesc: 'Ingrese sus credenciales para acceder a su cuenta',
      signUpDesc: 'Ingrese sus datos para comenzar',
      login: 'Acceso',
      signUp: 'Inscribirse',
      fullName: 'Nombre Completo',
      email: 'Correo',
      password: 'Contraseña',
      forgotPassword: '¿Olvidó la contraseña?',
      signIn: 'Entrar',
      signingIn: 'Iniciando sesión...',
      creatingAccount: 'Creando cuenta...',
      createAccountButton: 'Crear Cuenta',
      or: 'O',
      loginWithEmailCode: 'Iniciar sesión con código de correo',
      resetPassword: 'Restablecer Contraseña',
      resetPasswordDesc: 'Ingrese su correo electrónico y le enviaremos un código para restablecer su contraseña.',
      sendResetCode: 'Enviar Código de Restablecimiento',
      backToLogin: 'Volver al Login',
      verifyEmail: 'Verifique su correo',
      verifyEmailDesc: 'Ingrese el código enviado para completar su registro.',
      verificationCode: 'Código de Verificación',
      verifying: 'Verificando...',
      verifyCode: 'Verificar Código',
      setNewPassword: 'Establecer Nueva Contraseña',
      setNewPasswordDesc: 'Ingrese el código enviado y su nueva contraseña.',
      newPassword: 'Nueva Contraseña',
      resetting: 'Restableciendo...',
      checkYourEmail: 'Revise su correo',
      checkEmailSent: 'Hemos enviado un código de verificación a',
      tryAgain: 'Intentar de nuevo',
      didntReceiveCode: '¿No recebeu el código?',
      useDifferentEmail: 'Usar correo diferente',
      securedBy: 'Protegido por',
      emailCodeSent: '¡Código enviado! Revise su correo.',
      passwordResetSent: '¡Código de restablecimiento enviado!',
      passwordResetSuccess: '¡Contraseña restablecida con éxito!',
      accountCreatedSuccess: '¡Cuenta creada con éxito!',
      loginSuccess: '¡Inicio de sesión con éxito!',
      enterEmailForCode: 'Por favor, ingrese su correo electrónico para recibir un código.',
    },
    landing: {
      projectManagement: 'Gestión de Proyectos',
      projectManagementDesc: 'Organice proyectos con tareas, subtareas y dependencias',
      teamCollaboration: 'Colaboración de Equipo',
      teamCollaborationDesc: 'Control de acceso basado en roles para grupos de trabajo y proyectos',
      multipleViews: 'Múltiples Vistas',
      multipleViewsDesc: 'Vistas de Lista, Calendario, Gantt y tablero Kanban',
      progressTracking: 'Seguimiento de Progreso',
      progressTrackingDesc: 'Monitoree el progreso de las tareas y los cronogramas de los proyectos',
      heroTitle: 'Gestione Proyectos con',
      heroClarity: ' Claridad',
      heroDesc: 'Potente gestión de proyectos con RBAC, múltiples vistas e integración con Microsoft 365. Construido con los principios de Material Design 3.',
      startFree: 'Empezar Gratis',
      learnMore: 'Más Información',
      everythingYouNeed: 'Todo lo que necesitas',
      comprehensiveTools: 'Herramientas integrales para la gestión de proyectos moderna',
      readyToGetStarted: '¿Listo para comenzar?',
      joinTeams: 'Únase a los equipos que usan ProjecTrak para gestionar sus proyectos de manera eficiente',
      createFreeAccount: 'Crear Cuenta Gratis',
      builtWith: 'Desarrollado por',
      materialDesign: 'Gestión de Proyectos en Material Design',
    },
  },
};
